import React, { useState, useRef, useEffect } from 'react';
import { Upload, RefreshCw, FileUp, X, Check, Brain, ChevronDown, Download, ZoomIn, RotateCcw } from 'lucide-react';
import type { EmbryoResult } from '../types/embryo';

interface AssessmentHubProps {
    embryos: EmbryoResult[];
    setEmbryos: React.Dispatch<React.SetStateAction<EmbryoResult[]>>;
}

export function AssessmentHub({ embryos, setEmbryos }: AssessmentHubProps) {
    console.log('[AssessmentHub] render start');
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [isProcessing, setIsProcessing] = useState(false);
    const [successMessage, setSuccessMessage] = useState<string>('');
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Generate dynamic cycle ID based on current date
    const currentDate = new Date();
    const cycleNumber = embryos.length > 0 ? Math.ceil(embryos.length / 6) : 1;
    const [selectedCycle, setSelectedCycle] = useState(`PT-${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}${String(currentDate.getDate()).padStart(2, '0')} - Cycle ${cycleNumber}`);

    const handleGenerateReport = () => {
        if (embryos.length === 0) {
            alert('No embryos to generate report. Please analyze at least one embryo first.');
            return;
        }

        // Create report content
        const reportContent = `
EMBRYA - EMBRYO ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
Patient Cycle: ${selectedCycle}
Total Embryos Analyzed: ${embryos.length}

${'='.repeat(80)}

SUMMARY STATISTICS
${'='.repeat(80)}
Average Viability Score: ${Math.round(embryos.reduce((sum, e) => sum + e.viabilityScore, 0) / embryos.length)}%
Highest Score: ${Math.max(...embryos.map(e => e.viabilityScore))}%
Lowest Score: ${Math.min(...embryos.map(e => e.viabilityScore))}%

${'='.repeat(80)}

DETAILED EMBRYO ANALYSIS
${'='.repeat(80)}

${embryos.map((embryo, index) => `
EMBRYO ${index + 1}: ${embryo.name}
${'─'.repeat(80)}
Rank: #${embryo.rank}
Viability Score: ${embryo.viabilityScore}%
Developmental Stage: ${embryo.features.developmentalStage}
Symmetry: ${embryo.features.symmetry}
Fragmentation: ${embryo.features.fragmentation}
${embryo.features.blastocystExpansion ? `Blastocyst Expansion: Grade ${embryo.features.blastocystExpansion}` : ''}
${embryo.features.innerCellMass ? `Inner Cell Mass: Grade ${embryo.features.innerCellMass}` : ''}
${embryo.features.trophectoderm ? `Trophectoderm: Grade ${embryo.features.trophectoderm}` : ''}

Key Findings:
${embryo.keyFindings.map(finding => `  • ${finding}`).join('\n')}

Recommendation: ${embryo.recommendation}
Analysis Date: ${embryo.uploadedAt ? embryo.uploadedAt.toLocaleString() : 'N/A'}
`).join('\n' + '='.repeat(80) + '\n')}

${'='.repeat(80)}

TRANSFER RECOMMENDATIONS
${'='.repeat(80)}

Top 3 Recommended for Transfer:
${embryos.slice(0, 3).map((e, i) => `${i + 1}. ${e.name} - Score: ${e.viabilityScore}% - ${e.recommendation}`).join('\n')}

${'='.repeat(80)}

NOTES:
- This report is generated using ensemble prediction from 3 models
- All scores and recommendations should be reviewed by a qualified embryologist
- Transfer decisions should consider additional clinical factors

Report generated by EMBRYA Platform
        `.trim();

        // Create and download the report
        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Embryo_Analysis_Report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        setSuccessMessage('Report generated and downloaded successfully!');
        setTimeout(() => setSuccessMessage(''), 3000);
    };

    const handleDragOver = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(true);
    };

    const handleDragLeave = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(false);
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(false);
        if (e.dataTransfer.files && e.dataTransfer.files[0]) {
            // Validate file type
            const file = e.dataTransfer.files[0];
            if (file.type.startsWith('image/')) {
                setSelectedFile(file);
                // Clear success message when new file is selected
                setSuccessMessage('');
            }
        }
    };

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        console.log('[AssessmentHub] file input change fired');
        if (e.target.files && e.target.files[0]) {
            console.log('[AssessmentHub] file selected', e.target.files[0].name, e.target.files[0].size, e.target.files[0].type);
            setSelectedFile(e.target.files[0]);
            // Clear success message when new file is selected
            setSuccessMessage('');
        }
    };

    const handleProcess = async () => {
        if (!selectedFile) {
            alert('Please select an image first');
            return;
        }

        setIsProcessing(true);
        console.log('=== STARTING IMAGE PROCESSING ===');
        console.log('File:', selectedFile.name, 'Size:', selectedFile.size, 'Type:', selectedFile.type);

        try {
            const formData = new FormData();
            formData.append('file', selectedFile);

            const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:8000';
            const url = `${apiBase.replace(/\/$/, '')}/predict`;
            console.log('[handleProcess] Fetching from:', url);

            console.log('[handleProcess] Calling fetch...');
            const response = await fetch(url, {
                method: 'POST',
                body: formData
            });
            
            console.log('[handleProcess] Fetch returned - Status:', response.status, 'StatusText:', response.statusText);
            
            if (!response.ok) {
                const errorText = await response.text();
                console.error('[handleProcess] Error response text:', errorText);
                throw new Error(`Backend error: ${response.status} - ${errorText.substring(0, 200)}`);
            }

            console.log('[handleProcess] Response OK, parsing JSON...');
            const data = await response.json();
            console.log('[handleProcess] JSON parsed successfully:', JSON.stringify(data, null, 2));

            if (data.viability_score === undefined || data.viability_score === null) {
                throw new Error('Invalid response: missing viability_score');
            }

            console.log('[handleProcess] Creating embryo object...');

            // Map backend response to EmbryoResult
            const newEmbryo: EmbryoResult = {
                id: `emb-${Date.now()}`,
                name: `EMB-${String(embryos.length + 1).padStart(3, '0')}`,
                imageUrl: URL.createObjectURL(selectedFile),
                viabilityScore: Math.round(data.viability_score),
                rank: embryos.length + 1,
                features: {
                    developmentalStage: 'Day 5 Blastocyst',
                    symmetry: data.confidence_level === 'high' ? 'Excellent' : data.confidence_level === 'medium' ? 'Good' : 'Fair',
                    fragmentation: data.features.edge_density < 0.1 ? '<5% (Minimal)' : data.features.edge_density < 0.2 ? '5-10% (Moderate)' : '>10% (High)',
                    blastocystExpansion: data.features.circularity > 0.8 ? '4' : data.features.circularity > 0.6 ? '3' : '2',
                    innerCellMass: data.features.std_dev > 40 ? 'A' : data.features.std_dev > 30 ? 'B' : 'C',
                    trophectoderm: data.features.entropy > 5 ? 'A' : data.features.entropy > 4 ? 'B' : 'C'
                },
                keyFindings: [
                    data.prediction === 'good' ? 'High viability detected' : 'Lower viability detected',
                    `Confidence: ${data.confidence_level}`,
                    `Ensemble prediction from 3 models`
                ],
                recommendation: data.viability_score >= 70 ? 'Suitable for transfer' : data.viability_score >= 50 ? 'Consider for transfer with caution' : 'Not recommended for transfer',
                uploadedAt: new Date(),
                processingStatus: 'completed'
            };

            console.log('[handleProcess] New embryo created:', newEmbryo.name, 'Score:', newEmbryo.viabilityScore);

            // Add new embryo and re-sort by viability score
            const updatedEmbryos = [...embryos, newEmbryo];
            
            // Sort by viability score (highest first) and update ranks
            updatedEmbryos.sort((a, b) => b.viabilityScore - a.viabilityScore);
            updatedEmbryos.forEach((embryo, index) => {
                embryo.rank = index + 1;
            });
            
            console.log('[handleProcess] Updating state with', updatedEmbryos.length, 'embryos');
            setEmbryos(updatedEmbryos);
            // Keep selectedFile so image remains visible until new file is selected
            
            // Show success message (stays visible until new upload)
            setSuccessMessage(`✓ ${newEmbryo.name} analyzed! Viability: ${newEmbryo.viabilityScore}% | Rank: #${newEmbryo.rank}`);
            
            console.log('[handleProcess] === PROCESSING COMPLETE ===');
            console.log('[handleProcess] Total embryos now:', updatedEmbryos.length);
        } catch (error) {
            console.error('[handleProcess] === PROCESSING FAILED ===');
            console.error('[handleProcess] Error details:', error);
            
            let errorMessage = 'Unknown error occurred';
            if (error instanceof Error) {
                errorMessage = error.message;
            }
            
            console.error('[handleProcess] Error message:', errorMessage);
            alert(`❌ Failed to process image:\n\n${errorMessage}\n\nTroubleshooting:\n1. Check backend logs\n2. Verify backend is running on http://127.0.0.1:8000\n3. Check console for detailed errors`);
        } finally {
            setIsProcessing(false);
            console.log('[handleProcess] Processing state reset');
        }
    };

    return (
        <div className="space-y-6 w-full max-w-screen-2xl mx-auto px-2 sm:px-4">
            {/* Success Message */}
            {successMessage && (
                <div className="bg-green-50 border border-green-200 rounded-lg p-4 flex items-center gap-3 animate-fade-in">
                    <Check className="size-5 text-green-600 flex-shrink-0" />
                    <p className="text-sm font-medium text-green-800">{successMessage}</p>
                    <button 
                        onClick={() => setSuccessMessage('')}
                        className="ml-auto text-green-600 hover:text-green-800"
                    >
                        <X className="size-4" />
                    </button>
                </div>
            )}
            
            {/* Header */}
            <div className="flex items-center justify-between gap-4 flex-wrap">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Embryo Assessment Hub</h1>
                    <p className="text-gray-500">Automated morphological analysis and viability scoring workspace</p>
                </div>
                <div className="flex gap-3 flex-wrap">
                    <div className="flex items-center gap-2 text-sm bg-gray-100 px-3 py-1.5 rounded-full border border-gray-200">
                        <span className="font-semibold text-gray-900">{embryos.length}</span>
                        <span className="text-gray-600">Embryos Analyzed</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-blue-600 bg-blue-50 px-3 py-1.5 rounded-full">
                        <RefreshCw className="size-4 animate-spin-slow" />
                        Real-time Processing
                    </div>
                    <button 
                        onClick={handleGenerateReport}
                        disabled={embryos.length === 0}
                        className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-colors ${
                            embryos.length === 0 
                                ? 'bg-gray-300 text-gray-500 cursor-not-allowed' 
                                : 'bg-blue-600 text-white hover:bg-blue-700'
                        }`}
                    >
                        <FileUp className="size-4" />
                        Generate Report
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 lg:gap-8">
                {/* Left Primary Column */}
                <div className="col-span-12 xl:col-span-8 space-y-6">
                    {/* Patient Selection */}
                    <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
                        <div className="flex items-center justify-between mb-2">
                            <label className="text-sm font-semibold text-gray-700 flex items-center gap-2">
                                <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                                Active Patient Cycle
                            </label>
                            <button className="text-blue-600 text-sm hover:underline">View History</button>
                        </div>

                        <div className="flex gap-4">
                            <div className="flex-1 relative">
                                <select
                                    value={selectedCycle}
                                    onChange={(e) => setSelectedCycle(e.target.value)}
                                    className="w-full appearance-none bg-gray-50 border border-gray-200 rounded-lg px-4 py-3 text-gray-900 font-medium focus:outline-none focus:ring-2 focus:ring-blue-500"
                                >
                                    <option>PT-2026-0124 - Cycle 3</option>
                                    <option>PT-2026-0124 - Cycle 2</option>
                                    <option>PT-2026-0098 - Cycle 1</option>
                                </select>
                                <ChevronDown className="absolute right-3 top-3.5 size-5 text-gray-500 pointer-events-none" />
                            </div>
                            <button className="px-4 py-2 text-gray-700 border border-gray-200 rounded-lg hover:bg-gray-50 font-medium">
                                Cycle Details
                            </button>
                        </div>
                    </div>

                    {/* Image Analysis Section */}
                    <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm flex-1 flex flex-col min-h-[520px]">
                        <div className="flex justify-between items-center mb-6">
                            <div>
                                <h3 className="text-lg font-semibold text-gray-900 border-l-4 border-blue-500 pl-3">Embryo Image Analysis</h3>
                                <p className="text-sm text-gray-500 pl-4 mt-1">High-Resolution Morphological Inspection</p>
                            </div>
                            <div className="flex gap-2">
                                <button className="px-3 py-1.5 bg-gray-100 text-gray-700 text-sm rounded-lg hover:bg-gray-200 transition-colors font-medium">Measurements</button>
                                <button className="px-3 py-1.5 border border-gray-200 text-gray-700 text-sm rounded-lg flex items-center gap-1 hover:bg-gray-50">
                                    <Download className="size-3" /> Export
                                </button>
                            </div>
                        </div>

                        <div className="flex gap-4 mb-4">
                            <div className="flex items-center gap-3 bg-gray-50 px-4 py-2 rounded-lg border border-gray-200 flex-1">
                                <ZoomIn className="size-5 text-gray-500" />
                                <span className="text-sm font-medium text-gray-700">Zoom Level</span>
                                <div className="h-4 w-[1px] bg-gray-300 mx-2"></div>
                                <span className="text-sm font-bold text-gray-900 ml-auto">100%</span>
                            </div>
                            <button className="w-12 flex items-center justify-center border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-600">
                                <RotateCcw className="size-5" />
                            </button>
                        </div>

                        <div className="flex-1 bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl flex items-center justify-center relative overflow-hidden group border border-gray-700 shadow-inner min-h-[360px]">
                            {selectedFile ? (
                                <img
                                    src={URL.createObjectURL(selectedFile)}
                                    alt="Analysis Target"
                                    className="w-full h-full object-contain"
                                />
                            ) : (
                                <div className="text-center">
                                    <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-4 backdrop-blur-sm">
                                        <Brain className="size-8 text-blue-400 opacity-50" />
                                    </div>
                                    <p className="text-gray-400 font-medium">No Active Image Selected</p>
                                    <p className="text-gray-500 text-sm mt-1">Select an image from the batch processor</p>
                                </div>
                            )}

                            {isProcessing && (
                                <div className="absolute inset-0 bg-black/70 backdrop-blur-sm flex flex-col items-center justify-center gap-3 text-white">
                                    <RefreshCw className="size-6 animate-spin" />
                                    <p className="font-semibold">Processing image...</p>
                                    <p className="text-xs text-blue-100 font-mono">Streaming features + ensemble prediction</p>
                                </div>
                            )}

                            <div className="absolute bottom-4 right-4 px-3 py-1.5 bg-black/60 backdrop-blur-md text-white text-xs font-mono rounded-lg border border-white/10 flex items-center gap-2">
                                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                                4096 x 4096 px
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right Secondary Column */}
                <div className="col-span-12 xl:col-span-4 space-y-6">
                    {/* Batch Processing / Upload */}
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
                            <Upload className="size-24 text-blue-600" />
                        </div>

                        <div className="flex justify-between items-start mb-6 relative z-10">
                            <div>
                                <h3 className="font-bold text-gray-900 text-lg">Image Upload</h3>
                                <p className="text-sm text-gray-500 mt-1 max-w-[250px]">Upload embryo image for AI analysis</p>
                            </div>
                            <div className="bg-blue-50 p-2 rounded-lg">
                                <Upload className="size-5 text-blue-600" />
                            </div>
                        </div>

                        <div
                            onDragOver={handleDragOver}
                            onDragLeave={handleDragLeave}
                            onDrop={handleDrop}
                            onClick={() => fileInputRef.current?.click()}
                            className={`
                border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-all duration-200 relative z-10
                ${isDragging ? 'border-blue-500 bg-blue-50 scale-[1.02]' : 'border-gray-300 hover:border-blue-400 hover:bg-gray-50'}
                ${selectedFile ? 'bg-blue-50/30 border-blue-200' : ''}
              `}
                        >
                            <input
                                type="file"
                                ref={fileInputRef}
                                className="hidden"
                                onChange={handleFileSelect}
                                accept="image/*"
                            />

                            {selectedFile ? (
                                <div className="flex items-center gap-4 text-left">
                                    <div className="w-16 h-16 bg-white rounded-lg shadow-sm border border-gray-200 p-1 flex-shrink-0">
                                        <img
                                            src={URL.createObjectURL(selectedFile)}
                                            alt="Preview"
                                            className="w-full h-full object-cover rounded"
                                        />
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <p className="font-semibold text-gray-900 truncate">{selectedFile.name}</p>
                                        <p className="text-sm text-gray-500">{(selectedFile.size / 1024).toFixed(1)} KB • Ready</p>
                                    </div>
                                    <button
                                        onClick={(e) => { e.stopPropagation(); setSelectedFile(null); }}
                                        className="p-2 hover:bg-red-50 text-red-500 rounded-full transition-colors"
                                    >
                                        <X className="size-5" />
                                    </button>
                                </div>
                            ) : (
                                <div className="py-4">
                                    <div className="w-16 h-16 bg-blue-100/50 rounded-full flex items-center justify-center mx-auto mb-4">
                                        <FileUp className="size-8 text-blue-600" />
                                    </div>
                                    <p className="text-lg font-semibold text-gray-900">Click to upload or drag & drop</p>
                                    <p className="text-sm text-gray-500 mt-2">Supports JPG, PNG, TIFF (Max 50MB)</p>
                                </div>
                            )}
                        </div>

                        <button
                            disabled={!selectedFile || isProcessing}
                            onClick={(e) => {
                                console.log('[AssessmentHub] process button click', {
                                    hasFile: !!selectedFile,
                                    isProcessing
                                });
                                e.stopPropagation();
                                handleProcess();
                            }}
                            className={`w-full mt-6 py-4 rounded-xl flex items-center justify-center gap-3 font-semibold text-lg transition-all shadow-md hover:shadow-lg ${!selectedFile || isProcessing
                                ? 'bg-gray-100 text-gray-400 cursor-not-allowed shadow-none'
                                : 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:opacity-90 active:scale-[0.98]'
                                }`}
                        >
                            {isProcessing ? (
                                <>
                                    <RefreshCw className="size-5 animate-spin" />
                                    Processing Analysis...
                                </>
                            ) : (
                                <>
                                    <Brain className="size-6" />
                                    Process Batch {selectedFile ? '(1)' : ''}
                                </>
                            )}
                        </button>
                    </div>

                    {/* Viability Score Card - Only show when success message exists (after processing) */}
                    {successMessage && (
                        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                            <div className="flex justify-between items-start mb-6">
                                <div>
                                    <h3 className="font-bold text-gray-900 text-lg">Latest Analysis</h3>
                                    <p className="text-sm text-gray-500">Most recent embryo viability</p>
                                </div>
                                <span className="bg-green-100 text-green-700 text-xs font-bold px-3 py-1.5 rounded-full flex items-center gap-1.5">
                                    <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse" />
                                    LIVE
                                </span>
                            </div>

                            <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-4">
                                <div className="flex items-start gap-3">
                                    <Check className="size-5 text-green-600 flex-shrink-0 mt-0.5" />
                                    <div className="flex-1">
                                        <p className="text-sm font-semibold text-green-800">{successMessage}</p>
                                        <p className="text-xs text-green-600 mt-1">Analysis complete and saved</p>
                                    </div>
                                </div>
                            </div>

                            {embryos.length > 0 && (
                                <div className="grid grid-cols-2 gap-4 pt-6 border-t border-gray-100">
                                    <div className="p-3 bg-gray-50 rounded-lg text-center">
                                        <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider mb-1">Total Analyzed</p>
                                        <p className="text-gray-900 font-bold">{embryos.length}</p>
                                    </div>
                                    <div className="p-3 bg-gray-50 rounded-lg text-center">
                                        <p className="text-xs text-gray-500 font-semibold uppercase tracking-wider mb-1">Avg Score</p>
                                        <p className="text-gray-900 font-bold">
                                            {Math.round(embryos.reduce((sum, e) => sum + e.viabilityScore, 0) / embryos.length)}
                                        </p>
                                    </div>
                                </div>
                            )}
                        </div>
                    )}

                    {/* Analyzed Embryos List */}
                    {embryos.length > 0 && (
                        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                            <div className="flex justify-between items-center mb-4">
                                <h3 className="font-bold text-gray-900 text-lg">Analyzed Embryos</h3>
                                <span className="text-xs text-gray-500">{embryos.length} total</span>
                            </div>
                            <div className="space-y-2 max-h-64 overflow-y-auto">
                                {embryos.slice().reverse().map((embryo) => (
                                    <div key={embryo.id} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                                        <img 
                                            src={embryo.imageUrl} 
                                            alt={embryo.name}
                                            className="w-12 h-12 object-cover rounded-lg border border-gray-200"
                                        />
                                        <div className="flex-1 min-w-0">
                                            <p className="font-semibold text-gray-900 text-sm">{embryo.name}</p>
                                            <p className="text-xs text-gray-500">Rank #{embryo.rank}</p>
                                        </div>
                                        <div className="text-right">
                                            <p className={`font-bold text-lg ${
                                                embryo.viabilityScore >= 80 ? 'text-green-600' :
                                                embryo.viabilityScore >= 70 ? 'text-blue-600' :
                                                embryo.viabilityScore >= 50 ? 'text-amber-600' : 'text-red-600'
                                            }`}>
                                                {embryo.viabilityScore}%
                                            </p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Status Panel */}
                    <div className="bg-gradient-to-r from-gray-900 to-gray-800 p-5 rounded-xl text-white shadow-lg flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center">
                                <Check className="size-5 text-green-400" />
                            </div>
                            <div>
                                <p className="font-semibold">System Operational</p>
                                <p className="text-xs text-gray-400">All 3 models loaded</p>
                            </div>
                        </div>
                        <div className="text-right">
                            <p className="text-2xl font-bold">{embryos.length}</p>
                            <p className="text-xs text-gray-400">Processed in Session</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}
